name: fire_storages
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
 sdk: '>=3.4.1 <4.0.0'


dependencies:
 flutter:
  sdk: flutter
 cupertino_icons: ^1.0.6
 firebase_storage: ^12.0.0
 firebase_core: ^3.0.0
 path_provider: ^2.1.3
 cached_network_image: ^3.3.1
 image_picker: ^1.1.2
 wechat_assets_picker: ^9.0.3
 file_picker: ^8.0.3
 video_player: ^2.8.6
 audioplayers: ^6.0.0
 http: ^1.2.1




dev_dependencies:
 flutter_test:
  sdk: flutter
 flutter_lints: ^3.0.0

flutter:
 uses-material-design: true